==========================================
SLURM_JOB_ID = 16577798
SLURM_JOB_NODELIST = d13-09
TMPDIR = /tmp/SLURM_16577798
==========================================
2023-09-02 19:23:15,120 - A matching Triton is not available, some optimizations will not be enabled.
Error caught was: No module named 'triton'
Traceback (most recent call last):
  File "/project/ajoshi_27/akrami/3D_lesion_DF/3d_ddpm.py", line 227, in <module>
    df = pd.read_csv(csvpath)
  File "/home1/akrami/.conda/envs/working_monai/lib/python3.9/site-packages/pandas/util/_decorators.py", line 211, in wrapper
    return func(*args, **kwargs)
  File "/home1/akrami/.conda/envs/working_monai/lib/python3.9/site-packages/pandas/util/_decorators.py", line 331, in wrapper
    return func(*args, **kwargs)
  File "/home1/akrami/.conda/envs/working_monai/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 950, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home1/akrami/.conda/envs/working_monai/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 605, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/home1/akrami/.conda/envs/working_monai/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 1442, in __init__
    self._engine = self._make_engine(f, self.engine)
  File "/home1/akrami/.conda/envs/working_monai/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 1735, in _make_engine
    self.handles = get_handle(
  File "/home1/akrami/.conda/envs/working_monai/lib/python3.9/site-packages/pandas/io/common.py", line 856, in get_handle
    handle = open(
FileNotFoundError: [Errno 2] No such file or directory: '/patched-Diffusion-Models-UAD/Data/splits/IXI_train_fold0.csv'
